Repository DiegoFigueroaS/SCESI-GitAndGithub-ConflictoTeam, pull requests merged in 2025-05, with the labels that each got.

#8 feat: divide operation
  src/main/java/org/example/Services/DivideOperation.java
Labels: enhancement

#9 feat: interface operation strategy
  src/main/java/org/example/Services/MultiplyOperation.java
  src/main/java/org/example/Services/OperationStrategy.java
Labels: enhancement

#10 fix: errores en la division solucionados
  src/main/java/org/example/Services/DivideOperation.java
Labels: bug

#11 feat: readme actualizado
  README.md
  assets/ci_failed.png
  assets/ci_passed.png
  assets/conflicts.png
  assets/one_reviewer_parameter.png
  assets/pr_comments_validations.png
  assets/pr_template.png
Labels: documentation
